### ISSUE TITLE
【滝西】「その他」画面の時にヘッダー、フッターを出す

### ISSUE THREAD

**Issue by yasuraoka** [citytech-inc/Self-Order_Customer-Screen#103]

**Comment by ShotaYasuraoka** [comment]
・src -> pages -> tsxの中にSettingsScreen.tsxを追加する。
・pagesの中の他のファイルのヘッダー、フッターのつき方やその他のコードの書かれ方をみて、SettingsScreen.tsxにヘッダー、フッターを追加する。（ヘッダー、フッターのデザイン自体はsrc -> pages -> tsx -> Headerとかの中にあるから、今回cssファイルは恐らく不要。必要だったらごめん頑張って適切な場所にファイル作って）
