### ISSUE TITLE
客側スクリーンの動作完成

### ISSUE THREAD

**Issue by yasuraoka** [citytech-inc/Self-Order_Customer-Screen#11]
・ボタン押した時に狙い通りのスクリーンに行かせること。客側スクリーンは全て揃っているが、ポップアップがまだ完成されていないので横田の作業が完成次第そっちもお願い。
・注文時、カートに追加時のデータ保存はしなくていい

**Comment by yukiyamamoto0804** [comment]
・フッターの左側の四角いボタンの遷移
・メインスクリーン内のカテゴリーを押したときの表示の変更
を行った
ポップアップは横田の作業を待ってから行う
