### ISSUE TITLE
飼沼タスク（デザインの修正）

### ISSUE THREAD

**Issue by ShotaYasuraoka** [citytech-inc/Self-Order_Customer-Screen#76]
figmaの③、④、⑥のスクリーンのヘッダー、フッター部分以外のデザイン修正。スクリーンサイズの変化への対応、表示する文字が長すぎるときの対応などを行ってほしい。

【注意点】
・③のダイナミックプライシング表記対応はしなくて良い
・⑥の「注文」ボタンはデザイン上フッターの外部にあるようにも見えるが、スクロール範囲外なのでフッターに入れる。なので今回は何もしなくて良い。
・③のプルダウンの位置がおかしいから直してほしい
・⑤の「削除」、「変更」ボタンを押した後の挙動がおかしいが、そこは直さなくて良い
・⑥の表示が一部おかしいから直してほしい（安楽岡がサボっただけ）

**Comment by mpses** [comment]
#87
